[package]
name = "npack"
version = "0.0.20"
edition = "2021"
description = "Use the right package manager"
authors = ["fangyuan.leslie@gmail.com"]
keywords = ["npack", "cli", "package-manager", "ni", "npm"]
license = "MIT"
homepage = "https://github.com/zhazhazhu/ni"
repository = "https://github.com/zhazhazhu/ni"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ni"
path = "src/bin/ni.rs"
[[bin]]
name = "nr"
path = "src/bin/nr.rs"
[[bin]]
name = "nun"
path = "src/bin/nun.rs"
[[bin]]
name = "nlx"
path = "src/bin/nlx.rs"
[[bin]]
name = "nu"
path = "src/bin/nu.rs"
[[bin]]
name = "na"
path = "src/bin/na.rs"
[[bin]]
name = "nci"
path = "src/bin/nci.rs"

exclude = ["install.sh"]

[dependencies]
console = "0.15.7"
dirs = "5.0.1"
rust-ini = "0.20.0"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
serde = { version = "1.0.193", features = ["derive", "default"] }
serde_json = { version = "1.0.108", features = ["preserve_order"] }
tempfile = "3.8.1"
which = "5.0.0"
inquire = "0.6.2"
indexmap = { version = "2.1.0", features = ["serde"] }
